### ISSUE TITLE
metadata.csv 

### ISSUE THREAD

**Issue by merybolton** [angelettilab/scMouseBcellFlu#1]
Hi,	

I cannot proceed past the step of "INFER IG GENOTYPE AND ESTIMATE SEQ DIST THRESHOLD" of your pipeline:	

What is the metadata.csv that I need to input to the 01_VDJ_genotype_and_threshold.R script? I don't have such a file in my cellranger output nor in any of the earlier outputs from the pipeline.  	

Thank you beforehand!

Mery

**Comment by JonathanRob** [comment]
Hi Mery,

You're correct, the `metadata.csv` file is not generated by cellranger or any of the pipelines here. The `metadata.csv` file needs to be manually created before running the analysis, and should contain information corresponding to your data. As an example of what the file should look like, you can view the [`metadata.csv`](https://github.com/angelettilab/scMouseBcellFlu/blob/master/data/metadata.csv) file that is currently in the `data/` directory, which is the metadata file we used for our dataset. I've included a preview of the first few lines here:

| dataset | assay | chemistry | mouse_nr | infection | day_post_infection | organ | organ_day |
| ------- | ----- | --------- | -------- | --------- | ------------------ | ----- |---------- |
| spleen0_1 | rna | v2 | M7 | naive | D0 | spleen | spleen0 |
| spleen0_2 | rna | v2 | M8 | naive | D0 | spleen | spleen0 |
| spleen7_1 | rna | v2 | M9 | infected | D7 | spleen | spleen7 |
| spleen7_2 | rna | v2 | M10 | infected | D7 | spleen | spleen7 |
| spleen14_1 | rna | v2 | M1 | infected | D14 | spleen | spleen14 |
| spleen14_2 | rna | v2 | M2 | infected | D14 | spleen | spleen14 |
| spleen14_3 | rna | v2 | M3 | infected | D14 | spleen | spleen14 |
| ... | ... | ... | ... | ... | ... | ... | ... |

I have also updated the `README.md` file in the [`scripts/VDJ_analysis/`](https://github.com/angelettilab/scMouseBcellFlu/tree/master/scripts/VDJ_analysis) directory to explain this more clearly.

**Comment by JonathanRob** [comment]
I'm closing this issue, but please feel free to re-open if you continue to have problems!

**Comment by gt7901b** [comment]
@JonathanRob, Hi, Just read this nice paper (https://doi.org/10.1016/j.celrep.2021.109286). Will you please point me to the code and data file example that generate the alluvial plot like in Fig.5C? I could not find it in the scripts/plotting directory. thank you

**Comment by JonathanRob** [comment]
Hi @gt7901b, I'm glad you enjoyed the paper!

Unfortunately, I was not responsible for that particular analysis/plot, so I recommend contacting Davide (davide.angeletti@gu.se) for code/examples to generate that figure.
